seed: 1234
__set_torchseed: !apply:torch.manual_seed [!ref <seed>]

output_folder: !PLACEHOLDER  # e.g., "results/spatialeegnet_loso"
n_classes: 3
sample_rate: 128
fmin: 0.1
fmax: 50.0

tmin: 0.0
tmax: 4.0
paradigm: !new:moabb.paradigms.MotorImagery
  tmin: !ref <tmin>
  tmax: !ref <tmax>
  fmin: !ref <fmin>
  fmax: !ref <fmax>
  resample: !ref <sample_rate>

T: !apply:math.ceil
  - !ref <sample_rate> * (<tmax> - <tmin>)

datasets:
  - !new:moabb.datasets.BNCI2014_001
  - !new:moabb.datasets.Cho2017
  - !new:moabb.datasets.PhysionetMI

label_maps:
  BNCI2014_001: {left_hand: 0, right_hand: 1, feet: 2, tongue: 2}
  Cho2017: {left_hand: 0, right_hand: 1}
  PhysionetMI: {left_hand: 0, right_hand: 1}

cache_config:
  save_epochs: true
  use: true

# ========== Training ==========

number_of_epochs: 20
lr: 0.0001
batch_size: 8
pad_time: !ref <T>

loss: !name:speechbrain.nnet.losses.nll_loss
optimizer: !name:torch.optim.Adam
  lr: !ref <lr>

# ========== Evaluation ==========
test_with: "last"
test_key: "acc"
f1: !name:sklearn.metrics.f1_score
  average: "macro"
acc: !name:sklearn.metrics.balanced_accuracy_score
cm: !name:sklearn.metrics.confusion_matrix
metrics:
  f1: !ref <f1>
  acc: !ref <acc>
  cm: !ref <cm>

# ========== Model Configuration ==========

projection_dim: 22
spatial_focus_tau: 0.5

cnn_temporal_kernels: 40
cnn_temporal_kernelsize: 30
cnn_spatial_depth_multiplier: 2
cnn_spatial_max_norm: 1
cnn_spatial_pool: 4
cnn_septemporal_depth_multiplier: 1
cnn_septemporal_point_kernels: 64
cnn_septemporal_kernelsize: 15
cnn_septemporal_pool: 2
cnn_pool_type: "avg"
activation_type: "elu"
dense_max_norm: 0.25
dropout: 0.3

model: !new:models.SpatialEEGNet.SpatialEEGNet
  T: !ref <T>
  C: !ref <projection_dim>
  cnn_temporal_kernels: !ref <cnn_temporal_kernels>
  cnn_temporal_kernelsize: [!ref <cnn_temporal_kernelsize>, 1]
  cnn_spatial_depth_multiplier: !ref <cnn_spatial_depth_multiplier>
  cnn_spatial_max_norm: !ref <cnn_spatial_max_norm>
  cnn_spatial_pool: [!ref <cnn_spatial_pool>, 1]
  cnn_septemporal_depth_multiplier: !ref <cnn_septemporal_depth_multiplier>
  cnn_septemporal_point_kernels: !ref <cnn_septemporal_point_kernels>
  cnn_septemporal_kernelsize: [!ref <cnn_septemporal_kernelsize>, 1]
  cnn_septemporal_pool: [!ref <cnn_septemporal_pool>, 1]
  cnn_pool_type: !ref <cnn_pool_type>
  activation_type: !ref <activation_type>
  spatial_focus: !new:models.SpatialEEGNet.SpatialFocus
    projection_dim: !ref <projection_dim>
    position_dim: 3
    tau: !ref <spatial_focus_tau>
  dense_max_norm: !ref <dense_max_norm>
  dropout: !ref <dropout>
  dense_n_neurons: !ref <n_classes>
